language: node_js
sudo: false
node_js:
  - '6.9.5'

addons:
#  firefox: "38.0"
  apt:
    sources:
      # needed to install g++ that is used by npms's native modules
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  except:
    - g3_v2_0

cache:
  directories:
     - ./node_modules
     - ./.chrome/chromium

env:
  global:
    # GITHUB_TOKEN_ANGULAR=<github token, a personal access token of the angular-builds account, account access in valentine>
    # This is needed for the e2e Travis matrix task to publish packages to github for continuous packages delivery.
    - secure: "rNqXoy2gqjbF5tBXlRBy+oiYntO3BtzcxZuEtlLMzNaTNzC4dyMOFub0GkzIPWwOzkARoEU9Kv+bC97fDVbCBUKeyzzEqxqddUKhzRxeaYjsefJ6XeTvBvDxwo7wDwyxZSuWdBeGAe4eARVHm7ypsd+AlvqxtzjyS27TK2BzdL4="
  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
   - CI_MODE=js
   - CI_MODE=e2e
   - CI_MODE=saucelabs_required
   - CI_MODE=browserstack_required
   - CI_MODE=saucelabs_optional
   - CI_MODE=browserstack_optional

matrix:
  fast_finish: true
  allow_failures:
    - env: "CI_MODE=saucelabs_optional"
    - env: "CI_MODE=browserstack_optional"

install:
  - ./scripts/ci-lite/install.sh

script:
  - ./scripts/ci-lite/build.sh && ./scripts/ci-lite/test.sh

after_script:
  - ./scripts/ci-lite/cleanup.sh
